### ISSUE TITLE
README File Installation Details

### ISSUE THREAD

**Issue by DarioS** [FenyoLab/L1EM#1]
I am interested to install the software the old way. It has a list of dependencies to install, but I would also like to see instructions about how to install the L1EM Python software itself. Do I simply copy all of the Python code files into a directory listed in my `PYTHONPATH` variable or is there more to installing it? Also, there's a duplicated sentence in Output section.

> At completion, two tab delimited table will be written. At completion, three tab delimited tables will be written.

**Comment by wmckerrow** [comment]
No L1EM specific installation is necessary. In the current set up, you will pass the L1EM directory path to the pipeline shell script so that it can find all the python scripts and reference files. If you want to run the pipeline without having to enter the full path, you could add run_EM.sh to $PATH.

Thanks for pointing out the error in the README.
