### ISSUE TITLE
About L1EM/annotation/L1EM.400.bed

### ISSUE THREAD

**Issue by ChristopherLeeZG** [FenyoLab/L1EM#2]
Hello,

I find the gene  `L1TD1` 's loci in `hg38.gtf` from ucsc is  `chr1	ncbiRefSeq	transcript	62194849	62212328	.	+	.	gene_id "L1TD1"; transcript_id "NM_019079.5";  gene_name "L1TD1";`

But it is not in the file  `L1EM/annotation/L1EM.400.bed` . ( I use `bedtools intersect` to check it, still don't have overlap peak with `chr1 62194849	62212328`  .)
 
So if i find some RNA-seq files have highly `L1TD1`  express (use `featureCounts` and `hg38.gtf`,   bam files is used `hisat2`),  but it is not in this pipeline results file `full_counts.txt`.  

What should I do?  Should I add peak `chr1 62194849	62212328` to the file  `L1EM/annotation/L1EM.400.bed` ?

Thank you very much for your busy reading my issues.

**Comment by wmckerrow** [comment]
L1TD1 is a spliced protein coding gene derived from LINE-1 rather than a LINE-1 element. That is why it is not included in the reference. It shouldn't be similar enough to L1 for a significant number of L1 reads to misalign to it. I prefer to analyze genes (including L1TD1) separately using standard methods like featureCounts. If you want to add it to the L1EM.400.bed, make sure that you follow the same pattern in the name column. Something like "L1TD1.1.chr1:62194849-62212328.-".

**Comment by ChristopherLeeZG** [comment]
Thank you for your reading.
But sorry.  I  don't understand the sentence `It shouldn't be similar enough to L1 for a significant number of L1 reads to misalign to it.` .   Would you explain the sentence in detail.
Thank you !
